{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2023-29824",
      "description": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-29824",
      "reportURL": "https://github.com/scipy/scipy/issues/14713",
      "timeStamp": "2023-07-17T18:51:00Z"
    },
    {
      "id": "CVE-2023-29824",
      "description": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2023-29824",
      "reportURL": "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565",
      "timeStamp": "2023-07-17T18:51:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2023-29824",
      "url": "https://github.com/scipy/scipy/issues/14713",
      "added_at": "2023-09-23T10:56:34Z"
    },
    {
      "id": "CVE-2023-29824",
      "url": "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565",
      "added_at": "2023-09-23T10:56:34Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2023-29824",
      "url": "https://github.com/scipy/scipy/issues/14713",
      "added_at": "2023-07-17T18:51:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2023-29824",
      "url": "https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565",
      "added_at": "2023-07-17T18:51:00Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
