{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-9948",
      "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-9948",
      "reportURL": "https://bugs.python.org/issue35907",
      "timeStamp": "2020-08-24T17:37:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2019-9948",
      "url": "https://bugs.python.org/issue35907",
      "added_at": "1970-01-01T00:00:00Z"
    },
    {
      "id": "CVE-2019-9948",
      "url": "https://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
      "added_at": "2022-02-10T19:32:13Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-9948",
      "url": "https://bugs.python.org/issue35907",
      "added_at": "2020-08-24T17:37:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2019-9948",
      "url": "https://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
      "added_at": "2022-02-10T19:32:13Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
