{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-16226",
      "description": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node-\u003emn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-16226",
      "reportURL": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln",
      "timeStamp": "2020-09-14T15:21:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2019-16226",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln",
      "added_at": "1970-01-01T00:00:00Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-16226",
      "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln",
      "added_at": "2020-09-14T15:21:00Z",
      "score": 0,
      "template_for": ""
    }
  ]
}
