{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2019-14491",
      "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered\u003ccv::HaarEvaluator\u003e in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2019-14491",
      "reportURL": "https://github.com/opencv/opencv/issues/15125",
      "timeStamp": "2019-12-02T03:15:00Z"
    }
  ],
  "trickest": [],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2019-14491",
      "url": "https://github.com/opencv/opencv/issues/15125",
      "added_at": "2019-12-02T03:15:00Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
