{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2022-36087",
      "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-36087",
      "reportURL": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py",
      "timeStamp": "2022-09-15T03:35:00Z"
    },
    {
      "id": "CVE-2022-36087",
      "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-36087",
      "reportURL": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232",
      "timeStamp": "2022-09-15T03:35:00Z"
    },
    {
      "id": "CVE-2022-36087",
      "description": "OAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-36087",
      "reportURL": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
      "timeStamp": "2022-09-15T03:35:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2022-36087",
      "url": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
      "added_at": "2023-01-24T06:01:43Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [
    {
      "cve": "CVE-2022-36087",
      "url": "https://www.cve.news/cve-2022-36087/",
      "added_at": "2023-01-16T00:00:00Z",
      "score": 1,
      "template_for": ""
    }
  ],
  "openpoc": [
    {
      "cve": "CVE-2022-36087",
      "url": "https://github.com/oauthlib/oauthlib/blob/2b8a44855a51ad5a5b0c348a08c2564a2e197ea2/oauthlib/uri_validate.py",
      "added_at": "2022-09-15T03:35:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-36087",
      "url": "https://github.com/oauthlib/oauthlib/blob/d4bafd9f1d0eba3766e933b1ac598cbbf37b8914/oauthlib/oauth2/rfc6749/grant_types/base.py#L232",
      "added_at": "2022-09-15T03:35:00Z",
      "score": 0,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-36087",
      "url": "https://github.com/oauthlib/oauthlib/security/advisories/GHSA-3pgj-pg6c-r5p7",
      "added_at": "2022-09-15T03:35:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2022-36087",
      "url": "https://www.cve.news/cve-2022-36087/",
      "added_at": "2023-01-16T00:00:00Z",
      "score": 1,
      "template_for": ""
    }
  ]
}
