{
  "exploitdb": [],
  "itw": [
    {
      "id": "CVE-2008-7264",
      "description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
      "referenceURL": "https://nvd.nist.gov/vuln/detail/CVE-2008-7264",
      "reportURL": "https://code.google.com/p/pyftpdlib/issues/detail?id=71",
      "timeStamp": "2010-10-20T04:00:00Z"
    }
  ],
  "trickest": [
    {
      "id": "CVE-2008-7264",
      "url": "https://code.google.com/p/pyftpdlib/issues/detail?id=71",
      "added_at": "2022-06-03T01:47:42Z"
    },
    {
      "id": "CVE-2008-7264",
      "url": "https://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
      "added_at": "2022-06-03T01:47:42Z"
    }
  ],
  "nomisec": [],
  "nuclei": [],
  "metasploit": [],
  "holloways": [],
  "openpoc": [
    {
      "cve": "CVE-2008-7264",
      "url": "https://code.google.com/p/pyftpdlib/issues/detail?id=71",
      "added_at": "2010-10-20T04:00:00Z",
      "score": 0.4,
      "template_for": ""
    },
    {
      "cve": "CVE-2008-7264",
      "url": "https://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
      "added_at": "2022-06-03T01:47:42Z",
      "score": 0.4,
      "template_for": ""
    }
  ]
}
